// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN1AA9ZwSN0wGSFMwf-jqlC76SFlmH9k8',
    appId: '1:323883760267:web:c638f54e4b930af7e5728e',
    messagingSenderId: '323883760267',
    projectId: 'bible-chats',
    authDomain: 'bible-chats.firebaseapp.com',
    storageBucket: 'bible-chats.appspot.com',
    measurementId: 'G-6E53QM0502',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGpGxtcXj20a7k1ifZ56Q6kkXdmkqfUG4',
    appId: '1:323883760267:ios:533078c1cb348f5ee5728e',
    messagingSenderId: '323883760267',
    projectId: 'bible-chats',
    storageBucket: 'bible-chats.appspot.com',
    iosBundleId: 'com.assistine.bibleChat',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdaLJR06BLPZQ1F-khXaGF5byhU6PFrQs',
    appId: '1:323883760267:android:5a20ca64ff91a8aee5728e',
    messagingSenderId: '323883760267',
    projectId: 'bible-chats',
    storageBucket: 'bible-chats.appspot.com',
  );
}
